name: Run Journey Tests on GitHub

inputs:
  epr-re-ex-admin-frontend:
    required: false
    type: string
  branch:
    required: false
    type: string
    default: main
  journey-test-pr:
    required: false
    type: string
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository if not called by Journey Test PR
      if: inputs.journey-test-pr == 'false'
      uses: actions/checkout@v5
      with:
        repository: DEFRA/epr-re-ex-admin-frontend-tests
        ref: ${{inputs.branch}}

    - uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: npm
    - name: Setup the tests
      run: npm i
      shell: bash

    - name: Start docker compose
      shell: bash
      run: |
          EPR_RE_EX_ADMIN_FRONTEND=${{inputs.epr-re-ex-admin-frontend}} \
          docker compose up --wait-timeout 300 -d --quiet-pull

    - name: Run the tests
      shell: bash
      run: |
        npm run test:github
        npm run report
    - name: debug
      if: always()
      run: |
        docker compose logs > logs.txt
        docker ps
      shell: bash
    - name: Upload allure report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report
    - name: Upload docker compose logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: ./logs.txt
    - name: Fail this step if FAILED file exists
      if: always()
      run: |
        if [ -f "FAILED" ]; then
          exit 1
        fi
      shell: bash
