name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-prep:
    name: Preparation
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        uses: actions/github-script@v8
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const regex = /^(PAE-\d+)[-_]{1}.+$/i;
            const [match, ticketKey] = branchName.match(regex) ?? [null, null];

            if (!match || !ticketKey) {
              core.setFailed('Branch name does not match the required format: PAE-<NUMBER>-<desc>');
            } else {
              core.exportVariable('ticketKey', ticketKey.toUpperCase());
            }
      - name: Add ticket link to PR description
        uses: actions/github-script@v8
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { pull_request, repository } = context.payload;
            const { body: previousBody } = pull_request;
            const { ticketKey } = process.env;
            const ticketLink = `[${ticketKey}](https://eaflood.atlassian.net/browse/${ticketKey})`;

            if (!previousBody?.includes(ticketLink)) {
              github.rest.pulls.update({
                owner: repository.owner.login,
                repo: repository.name,
                pull_number: pull_request.number,
                body: `Ticket: ${ticketLink}\n${previousBody}`,
              });
            } else {
              console.log('PR description already contains a link to the ticket')
            }

  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    needs: pr-prep
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: |
          npm ci --ignore-scripts
          npm run format:check
          npm run lint

  tests:
    name: Run Journey Tests
    runs-on: ubuntu-latest
    steps:
      - uses: DEFRA/epr-re-ex-admin-frontend-tests/run-journey-tests@main


# Uncomment this to run the tests in your test suite
#  tests:
#    name: Run Journey Tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: DEFRA/cdp-node-journey-test-suite-template/run-journey-tests@main
